controller:
  hostPort:
    enabled: true
  service:
    type: ClusterIP
  nodeSelector:
    kubernetes.io/os: linux
    ingress-ready: "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule