apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  POSTGRES_DB: {{ .Values.db.name }}