apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskflow-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: taskflow-backend
  namespaceSelector:
    matchNames:
      - taskflow
  endpoints:
    - port: http
      path: /metrics
      interval: 15s