backend:
  image:
    repository: zloystudent/taskflow-backend
    tag: ec70285
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

frontend:
  image:
    repository: zloystudent/taskflow-frontend
    tag: ec70285
  replicaCount: 2

postgres:
  image: postgres:16-alpine
  storage: 1Gi

db:
  user: taskflow
  password: taskflow
  name: taskflow

ingress:
  host: taskflow.local